### PR TITLE
Chance for listeners (belongsToMany, MorphTo)

### PR DESCRIPTION
**Pull request by Volga**
Adds a chance for listeners of operations:

- attaching & detaching belongsToMany;
- associating & dissociating MorphTo.

### CODE REVIEW

**Comment by chelout** [comment]
First of all thanks for the contribution. Could you explain why should we break compatibility with native relation methods?

**Comment by Volga** [comment]
Hello! Because you initially missed this point. The code of the framework provides a chance for listeners in existing events.

https://github.com/laravel/framework/blob/5992f10116f612d51465385b0af11d778d975b87/src/Illuminate/Database/Eloquent/Model.php#L647

**Comment by chelout** [comment]
Well, now i see what your PR about. I have to think about it.

**Comment by Volga** [comment]
+

**Comment by Volga** [comment]
@chelout, Will there be any decision on request?

**Comment by chelout** [comment]
Hi, @Volga!
Going to merge your PR, but need to make some additional test and reflect this change in docs, but currently have enough time to do it :( Hope i can do it in this weekend or in the start of the next week.
Thanks again!

**Comment by chelout** [comment]
Added couple comments for your PR.
Also i would like to ask about other relations, shouldn't we provide such logic for methods in other relations?

**Pull request closed without merging**
