### PR TITLE
add laravel 5.5 compatibility

### PR DESCRIPTION
**Pull request by Vmak11**

### CODE REVIEW

**Comment by chelout** [comment]
You can check develop branch for laravel 5.5 compatibility fix

**Comment by Vmak11** [comment]
The issue with 5.5 compatibility is due to the fact it does not utilize the `new{Relationship}` methods such as  `newBelongsTo` that are getting overridden, those were added in 5.6, see this commit:
https://github.com/laravel/framework/commit/bb150d072cf0448862eba3d4ccd3ad9eab17520e#diff-a18aa0065696398ebfc40891576da288

**Comment by chelout** [comment]
Actually we doesn't care about when this methods were added, this package extends relation classes and also has new{relation} method, so it work in 5.5, 5.6 and 5.7. Tests could confirm this. Your PR just copied code from framework and fails travis ci tests.

**Comment by Vmak11** [comment]
I no longer have a need for this currently, without getting back to this and testing, I still don't think it will work on 5.5.  You are only overwriting the Illuminate relation classes within the new{relation} methods, so if they are never getting called, then your new relation classes are never instantiated and the Laravel ones are still used.  Basically the logic goes like this:

On Eloquent model, you will set up a relationship using
`$this-belongsTo(...args)`
which calls method within Illuminate HasRelationships Trait
On 5.5, that code never calls `newBelongsTo` that your code relies on to utilize your custom BelongsTo relation class and instead just news up the Illuminate BelongsTo relation class, which doesn't cause any errors but also doesn't fire any of your relationship events.

**Comment by chelout** [comment]
Could you provide me your tests?

**Pull request closed without merging**
