### PR TITLE
Renamed parameters in belongsToMany example

### PR DESCRIPTION
**Pull request by waltoncon**
And fixed a couple small spelling errors

### CODE REVIEW

**Comment by chelout** [comment]
Thanks for contribution, i'll check that tomorrow.

**Comment by chelout** [comment]
Thanks!

**Comment by chelout** [comment]
And congrats with the first contribution👍🏻🎉

**Comment by waltoncon** [comment]
No problem, thanks 😃

**Comment by chelout** [comment]
If you'd like, you can check the rest of the documentation, sure, there are lots of bugs...

**Pull request merged**
