### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by saleem-hadad**
Hi @chelout 

I've added tests directory with a basic setup to start with. Moreover, I've added tests each of:

+ HasOneEvents
+ HasManyEvents
+ HasMorphToEvents
+ HasBelongsToEvents
+ HasMorphOneEvents
+ HasMorphManyEvents
+ HasMorphToManyEvents
+ HasBelongsToManyEvents
+ HasMorphedByManyEvents

Thank you for creating this package.

### CODE REVIEW

**Comment by chelout** [comment]
@saleem-hadad thanks a lot for the contribution, i thought i'll never get my hands on tests)))
Are you going to write tests for all events?

**Comment by saleem-hadad** [comment]
You're welcome 👻
Yes I'll write, keep the PR open for now I'll add them gradually

**Comment by chelout** [comment]
I see you test if events are been dispatched, is it possible to test parameters of this events, i mean this case:
```php
...
        static::hasOneCreating(function ($parent, $related) {
            ...
        });
...
```

**Comment by saleem-hadad** [comment]
Sure! but I think that will be under unit level, however, I guess we can merge features and units cus I see them almost the same so that will reduce the code a bit, what do you think? or we should separate them 🤔

**Comment by chelout** [comment]
Sure we can merge them.

**Comment by saleem-hadad** [comment]
I've added one
see [here](https://github.com/chelout/laravel-relationship-events/pull/7/commits/771c84f4de4b27902c7633c3747474e3df5c5c94)

**Comment by saleem-hadad** [comment]
StyleCI is killing me 😤🤣

**Comment by chelout** [comment]
Don’t bother about StyleCI checks, i’ll take a moment to apply patch

**Comment by saleem-hadad** [comment]
Hi @chelout, Hope you have a nice day.
Sorry for being late but I was busy a bit. However, I'm done with the tests now 🤠 enjoy!
Thanks again for this nice package.

**Comment by chelout** [comment]
Hi @saleem-hadad!
Could you give me a hand with testing model observers?

**Pull request merged**
